name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y texlive-full

    - name: Build PDF
      run: make

    - name: Upload PDF
      uses: actions/upload-artifact@v4.6.2
      with: 
        name: PDF
        path: Penzin.pdf
